#!/bin/bash
#
# cntlm-config, Copyright 2005 Corinna Vinschen
#
# This file is part of the Cygwin port of Cntlm Proxy

# ======================================================================
# Initialization
# ======================================================================
PROGNAME=$(basename $0)
_tdir=$(dirname $0)
PROGDIR=$(cd $_tdir && pwd)

_required_csih_version=0.1.8
CSIH_SCRIPT=/usr/share/csih/cygwin-service-installation-helper.sh

# Subdirectory where the new package is being installed
PREFIX=/usr

# Directory where the config files are stored
SYSCONFDIR=/etc
DEVDIR=/dev
LOGDIR=/var/log
RUNDIR=/var/run

source ${CSIH_SCRIPT}
if ! csih_version_ge $csih_VERSION $_required_csih_version
then
  cntlmVER=$(cygcheck -cd cntlm | sed -n -e '/cntlm/p' | awk '{print $2}')
  csih_error_multi "cntlm-config version $cntlmVER requires csih-$_required_csih_version"
    "or above. You have csih-${csih_VERSION}. Please update the csih package."
fi

# ======================================================================
# Routine: install_service
#   Install cntlm as a service
# ======================================================================
install_service() {

  # Install cntlm service if it is not already installed
  if ! cygrunsrv -Q cntlm > /dev/null 2>&1
  then
    echo
    csih_warning "The following function requires administrator privileges!"
    if csih_request "Do you want to install syslogd as service?"
    then
      if cygrunsrv -I cntlm -d "CYGWIN Cntlm Authentication Proxy" -f "HTTP Accelerator" -p /usr/sbin/cntlm -1 /dev/null -2 /dev/null -a "-c ${SYSCONFDIR}/cntlm.conf -f"
      then
	  echo
	  csih_inform "The cntlm service has been installed under the LocalSystem"
	  csih_inform "account (also known as SYSTEM). To start the service now, call"
        csih_inform "\`net start cntlm' or \`cygrunsrv -S cntlm'. Otherwise, it"
        csih_inform "will start automatically after the next reboot."
	  echo
	  csih_inform "Check ${SYSCONFDIR}/cntlm.conf first, if it suits your needs."
      fi

      # now, if successfully installed, do some final configuration
      if cygrunsrv -Q cntlm >/dev/null 2>&1
      then
        chown SYSTEM.544 "${SYSCONFDIR}/cntlm.conf"
      else
        csih_warning "Something went wrong installing the cntlm service." 
      fi

    fi # user allowed us to install cntlm
  fi # cntlm already installed
} # --- End of install_service --- #


# ======================================================================
# Main Entry Point
# ======================================================================


# Check how the script has been started.  If
#   (1) it has been started by giving the full path and
#       that path is /etc/postinstall, OR
#   (2) Otherwise, if the environment variable
#       CNTLM_CONFIG_AUTO_ANSWER_NO is set
# then set auto_answer to "no".  This allows automatic
# creation of the config files in /etc w/o overwriting
# them if they already exist.  In both cases, color
# escape sequences are suppressed, so as to prevent
# cluttering setup's logfiles.
if [ "$PROGDIR" = "/etc/postinstall" ]
then
  csih_auto_answer="no"
  csih_disable_color
fi
if [ -n "${CNTLM_CONFIG_AUTO_ANSWER_NO}" ]
then
  csih_auto_answer="no"
  csih_disable_color
fi


# ======================================================================
# Parse options
# ======================================================================
while :
do
  case $# in
  0)
    break
    ;;
  esac

  option=$1
  shift

  case "$option" in
  -d | --debug )
    set -x
    csih_trace_on
    ;;

  -y | --yes )
    csih_auto_answer=yes
    ;;

  -n | --no )
    csih_auto_answer=no
    ;;

  *)
    echo "usage: ${PROGNAME} [OPTION]..."
    echo
    echo "This script creates a basic syslogd configuration."
    echo
    echo "Options:"
    echo "    --debug  -d     Enable shell's debug output."
    echo "    --yes    -y     Answer all questions with \"yes\" automatically."
    echo "    --no     -n     Answer all questions with \"no\" automatically."
    echo
    exit 1
    ;;

  esac
done

# ======================================================================
# Action!
# ======================================================================

# explicitly invoke _csih_setup early, to ensure basic directories
# exist and have correct permissions (/etc, /var/[log|run|empty])
_csih_setup

# Validate permissions on configuration file
chmod 644 "${SYSCONFDIR}/cntlm.conf"               >&/dev/null || /bin/true
setfacl -m u:system:rw- "${SYSCONFDIR}/cntlm.conf" >&/dev/null || /bin/true
setfacl -m g:544:rw- "${SYSCONFDIR}/cntlm.conf"    >&/dev/null || /bin/true
csih_check_access "${SYSCONFDIR}/cntlm.conf" "rw."

# maybe: csih_auto_answer=no will skip,
# interactive user will get a chance to override
install_service


echo
echo "Configuration finished. Have fun!"

