/**
 * WindowsVersionTable.cpp: Informations about all known Microsoft Windows versions.
 */

/**
 * From https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions
 * from https://www.gaijin.at/en/infos/windows-version-numbers
 *
 * copyright <C) 2018 - 2023 Various WEB contributors
 */

#include "SystemInfo.h"

const char *SystemInfo::WindowsVersionStr[] = {"Windows",
                                               "Windows 32s",
                                               "Windows 95",
                                               "Windows 95 SR1",
                                               "Windows 95 SR2",
                                               "Windows 95 SR2.5",
                                               "Windows 98",
                                               "Windows 98 SE",
                                               "Windows Me",
                                               "Windows NT 3.51",
                                               "Windows NT 3.51 Server",
                                               "Windows NT 4.0",
                                               "Windows NT 4.0 Server",
                                               "Windows 2000",
                                               "Windows XP",
                                               "Windows XP Professional x64",
                                               "Windows Home Server",
                                               "Windows Server 2003",
                                               "Windows Server 2003 R2",
                                               "Windows Vista",
                                               "Windows Server 2008",
                                               "Windows 7",
                                               "Windows Server 2008 R2",
                                               "Windows Home Server 2011",
                                               "Windows 8",
                                               "Windows Server 2012",
                                               "Windows 8.1",
                                               "Windows Server 2012 R2",
                                               "Windows 10",
                                               "Windows Server 2016",
                                               "Windows Server 2019",
                                               "Windows 11",
                                               "Windows Server 2022"};

const char *SystemInfo::WindowsEditionStr[] = {"Unknown product",
                                               "Work Station",
                                               "Server",
                                               "Advanced Server",
                                               "Home",
                                               "Ultimate",
                                               "Home Basic",
                                               "Home Premium",
                                               "Enterprise",
                                               "Home Basic N",
                                               "Business",
                                               "Server Standard",
                                               "Server Datacenter (full installation)",
                                               "Small Business Server",
                                               "Server Enterprise (full installation)",
                                               "Starter",
                                               "Server Datacenter (core installation)",
                                               "Server Standard (core installation)",
                                               "Server Enterprise (core installation)",
                                               "Server Enterprise for Itanium-based Systems",
                                               "Business N",
                                               "Web Server (full installation)",
                                               "HPC Edition",
                                               "Storage Essentials",
                                               "Storage Server Express",
                                               "Storage Server Standard",
                                               "Storage Server Workgroup",
                                               "Storage Server Enterprise",
                                               "Server for Windows Essential Server Solutions",
                                               "Small Business Server Premium",
                                               "Home Premium N",
                                               "Enterprise N",
                                               "Ultimate N",
                                               "Web Server (core installation)",
                                               "Essential Business Server Management Server",
                                               "Essential Business Server Security Server",
                                               "Essential Business Server Messaging Server",
                                               "Server Foundation",
                                               "Home Server",
                                               "Server without Hyper-V for Windows Essential Server Solutions",
                                               "Server Standard without Hyper-V",
                                               "Server Datacenter without Hyper-V (full installation)",
                                               "Server Enterprise without Hyper-V (full installation)",
                                               "Server Datacenter without Hyper-V (core installation)",
                                               "Server Standard without Hyper-V (core installation)",
                                               "Server Enterprise without Hyper-V (core installation)",
                                               "Microsoft Hyper-V Server",
                                               "Storage Server Express (core installation)",
                                               "Storage Server Standard (core installation)",
                                               "Storage Server Workgroup (core installation)",
                                               "Storage Server Enterprise (core installation)",
                                               "Starter N",
                                               "Professional",
                                               "Professional N",
                                               "Small Business Server 2011 Essentials",
                                               "Server For Small Business Solutions",
                                               "Server Solutions Premium",
                                               "Server Solutions Premium (core installation)",
                                               "Server For Small Business Solutions EM",
                                               "Server For Small Business Solutions EM",
                                               "MultiPoint Server",
                                               "Essential Server Solution Management",
                                               "Essential Server Solution core",
                                               "Essential Server Solution Additional",
                                               "Essential Server Solution Management SVC",
                                               "Essential Server Solution Additional SVC",
                                               "Small Business Server Premium (core installation)",
                                               "Server Hyper Core V",
                                               "Essential Server Solution",
                                               "Starter E",
                                               "Home Basic E",
                                               "Home Pemiux E",
                                               "Professional E",
                                               "Enterprise E",
                                               "Ultimate E",
                                               "Enterprise Evaluation",
                                               "MultiPoint Server Standard (full installation)",
                                               "MultiPoint Server Premium (full installation)",
                                               "Server Standard (evaluation installation)",
                                               "Server Datacenter (evaluation installation)",
                                               "Enterprise N Evaluation",
                                               "Essential Server Solution Automotive",
                                               "Essential Server Solution Industry A",
                                               "Thinpc",
                                               "Essential Server Solution A",
                                               "Essential Server Solution Industry",
                                               "Essential Server Solution E",
                                               "Essential Server Solution Industry E",
                                               "Essential Server Solution Industry A E",
                                               "Storage Server Workgroup (evaluation installation)",
                                               "Storage Server Standard (evaluation installation)",
                                               "Home ARM",
                                               "Home N",
                                               "Home China",
                                               "Home Single Language",
                                               "Home",
                                               "Professional with Media Center",
                                               "Mobile",
                                               "Education",
                                               "Education N",
                                               "Enterprise 2015 LTSB",
                                               "Enterprise 2015 LTSB N",
                                               "Enterprise 2015 LTSB Evaluation",
                                               "Enterprise 2015 LTSB N Evaluation",
                                               "Mobile Enterprise"};

const std::list<WindowsVersionInfo> SystemInfo::WindowsVersions = {
    /**
     * Old Windows Versions
     */
    {.m_szVersionName = "Windows 1.01",
     .m_szReleaseName = "",
     .m_szCodeName = "Interface Manager",
     .m_szReleaseDate = "1985-11-20",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {},
     .m_Version = WindowsBuildInfo(1, 1)},
    {.m_szVersionName = "Windows 1.02",
     .m_szReleaseName = "",
     .m_szCodeName = "",
     .m_szReleaseDate = "1986-05-14",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {},
     .m_Version = WindowsBuildInfo(1, 2)},
    {.m_szVersionName = "Windows 1.03",
     .m_szReleaseName = "",
     .m_szCodeName = "",
     .m_szReleaseDate = "1986-08-21",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {},
     .m_Version = WindowsBuildInfo(1, 3)},
    {.m_szVersionName = "Windows 1.04",
     .m_szReleaseName = "",
     .m_szCodeName = "",
     .m_szReleaseDate = "1987-04-10",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {},
     .m_Version = WindowsBuildInfo(1, 4)},
    {.m_szVersionName = "Windows 2.01",
     .m_szReleaseName = "",
     .m_szCodeName = "",
     .m_szReleaseDate = "1987-12-09",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {},
     .m_Version = WindowsBuildInfo(2, 1)},
    {.m_szVersionName = "Windows 2.03",
     .m_szReleaseName = "",
     .m_szCodeName = "",
     .m_szReleaseDate = "1987-12-09",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {},
     .m_Version = WindowsBuildInfo(2, 3)},
    {.m_szVersionName = "Windows 2.1",
     .m_szReleaseName = "",
     .m_szCodeName = "",
     .m_szReleaseDate = "1988-05-27",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {},
     .m_Version = WindowsBuildInfo(2, 10)},
    {.m_szVersionName = "Windows 2.11",
     .m_szReleaseName = "",
     .m_szCodeName = "",
     .m_szReleaseDate = "1989-03-13",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {},
     .m_Version = WindowsBuildInfo(2, 11)},

    /**
     * Windows 3x Versions
     */
    {.m_szVersionName = "Windows 3.0",
     .m_szReleaseName = "",
     .m_szCodeName = "",
     .m_szReleaseDate = "1990-05-22",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {"Windows 3.00a", "Windows 3.0 with Multimedia Extensions"},
     .m_Version = WindowsBuildInfo(3, 0)},
    {.m_szVersionName = "Windows 3.1",
     .m_szReleaseName = "",
     .m_szCodeName = "",
     .m_szReleaseDate = "1992-04-06",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {"Windows 3.1"},
     .m_Version = WindowsBuildInfo(3, 10, 103)},
    {.m_szVersionName = "Windows 3.1 for Workgroups",
     .m_szReleaseName = "",
     .m_szCodeName = "Sparta",
     .m_szReleaseDate = "1992-10-31",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {"Windows for Workgroups 3.1"},
     .m_Version = WindowsBuildInfo(3, 10, 102)},
    {.m_szVersionName = "Windows 3.11",
     .m_szReleaseName = "",
     .m_szCodeName = "",
     .m_szReleaseDate = "1993-11-08",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {"Windows 3.11"},
     .m_Version = WindowsBuildInfo(3, 11, 2)},
    {.m_szVersionName = "Windows 3.11 for Workgroups",
     .m_szReleaseName = "",
     .m_szCodeName = "Snowball",
     .m_szReleaseDate = "1993-11-08",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {"Windows for Workgroups 3.11"},
     .m_Version = WindowsBuildInfo(3, 11, 300)},
    {.m_szVersionName = "Windows 3.2",
     .m_szReleaseName = "",
     .m_szCodeName = "",
     .m_szReleaseDate = "1993-11-22",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {"Windows 3.2"},
     .m_Version = WindowsBuildInfo(3, 20, 153)},

    /**
     * Windows 9x versions
     */
    {.m_szVersionName = "Windows 95",
     .m_szReleaseName = "",
     .m_szCodeName = "Chicago",
     .m_szReleaseDate = "1995-08-24",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {"Windows 95"},
     .m_Version = WindowsBuildInfo(4, 0, 950)},
    {.m_szVersionName = "Windows 95 OEM Service Release 1",
     .m_szReleaseName = "",
     .m_szCodeName = "Chicago",
     .m_szReleaseDate = "1996-02-14",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {"Windows 95"},
     .m_Version = WindowsBuildInfo(4, 0, 950, false, false, 1)},
    {.m_szVersionName = "Windows 95 OEM Service Release 2",
     .m_szReleaseName = "",
     .m_szCodeName = "Chicago",
     .m_szReleaseDate = "1996-08-24",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {"Windows 95"},
     .m_Version = WindowsBuildInfo(4, 0, 950, false, false, 2)},
    {.m_szVersionName = "Windows 95 OEM Service Release 2.5",
     .m_szReleaseName = "",
     .m_szCodeName = "Chicago",
     .m_szReleaseDate = "1997-11-26",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {"Windows 95"},
     .m_Version = WindowsBuildInfo(4, 0, 950, false, false, 3)},
    {.m_szVersionName = "Windows 98",
     .m_szReleaseName = "",
     .m_szCodeName = "Memphis",
     .m_szReleaseDate = "1998-06-25",
     .m_szEolDate = "2006-07-11",
     .m_Editions = {"Windows 98"},
     .m_Version = WindowsBuildInfo(4, 10, 1998)},
    {.m_szVersionName = "Windows 98 Second Edition",
     .m_szReleaseName = "",
     .m_szCodeName = "",
     .m_szReleaseDate = "1999-05-05",
     .m_szEolDate = "2006-07-11",
     .m_Editions = {"Windows 98 Second Edition"},
     .m_Version = WindowsBuildInfo(4, 10, 2222)},
    {.m_szVersionName = "Windows Me",
     .m_szReleaseName = "",
     .m_szCodeName = "Millennium",
     .m_szReleaseDate = "2000-09-14",
     .m_szEolDate = "2006-07-11",
     .m_Editions = {"Windows Me"},
     .m_Version = WindowsBuildInfo(4, 90, 3000)},

    /**
     * Old Windows NT Versions
     */
    {.m_szVersionName = "Windows NT 3.1",
     .m_szReleaseName = "",
     .m_szCodeName = "Razzle",
     .m_szReleaseDate = "1993-07-27",
     .m_szEolDate = "2000-12-31",
     .m_Editions = {"Windows NT 3.1"},
     .m_Version = WindowsBuildInfo(3, 10, 511, true)},
    {.m_szVersionName = "Windows NT 3.1 Service Pack 3",
     .m_szReleaseName = "",
     .m_szCodeName = "Razzle",
     .m_szReleaseDate = "1994-11-01",
     .m_szEolDate = "2000-12-31",
     .m_Editions = {"Windows NT 3.1"},
     .m_Version = WindowsBuildInfo(3, 10, 528, true)},
    {.m_szVersionName = "Windows NT 3.5",
     .m_szReleaseName = "",
     .m_szCodeName = "Daytona",
     .m_szReleaseDate = "1994-09-21",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {"Windows NT 3.5 Workstation"},
     .m_Version = WindowsBuildInfo(3, 50, 807, true)},
    {.m_szVersionName = "Windows NT 3.51",
     .m_szReleaseName = "",
     .m_szCodeName = "Daytona",
     .m_szReleaseDate = "1995-05-30",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {"Windows NT 3.51 Workstation"},
     .m_Version = WindowsBuildInfo(3, 51, 1057, true)},
    {.m_szVersionName = "Windows NT 4.0",
     .m_szReleaseName = "",
     .m_szCodeName = "Shell Update Release",
     .m_szReleaseDate = "1996-08-24",
     .m_szEolDate = "2004-06-30",
     .m_Editions = {"Windows NT 4.0 Workstation"},
     .m_Version = WindowsBuildInfo(4, 0, 1381, true)},
    {.m_szVersionName = "Windows 2000",
     .m_szReleaseName = "",
     .m_szCodeName = "Windows NT 5.0",
     .m_szReleaseDate = "2000-02-17",
     .m_szEolDate = "2010-07-13",
     .m_Editions = {"Windows 2000 Professional"},
     .m_Version = WindowsBuildInfo(5, 0, 2195, true)},

    /**
     * Old Windows NT Server Versions
     */
    {.m_szVersionName = "Windows NT 3.1 Server",
     .m_szReleaseName = "",
     .m_szCodeName = "Razzle",
     .m_szReleaseDate = "1993-07-27",
     .m_szEolDate = "2000-12-31",
     .m_Editions = {"Windows NT 3.1 Advanced Server"},
     .m_Version = WindowsBuildInfo(3, 10, 528, true, true)},
    {.m_szVersionName = "Windows NT 3.5 Server",
     .m_szReleaseName = "",
     .m_szCodeName = "Daytona",
     .m_szReleaseDate = "1994-09-20",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {"Windows NT 3.5 Server"},
     .m_Version = WindowsBuildInfo(3, 50, 807, true, true)},
    {.m_szVersionName = "Windows NT 3.51 Server",
     .m_szReleaseName = "",
     .m_szCodeName = "Daytona",
     .m_szReleaseDate = "1995-05-29",
     .m_szEolDate = "2001-12-31",
     .m_Editions = {"Windows NT 3.51 Server"},
     .m_Version = WindowsBuildInfo(3, 51, 1057, true, true)},
    {.m_szVersionName = "Windows NT 4.0 Server",
     .m_szReleaseName = "",
     .m_szCodeName = "Shell Update Release",
     .m_szReleaseDate = "1996-07-29",
     .m_szEolDate = "2004-12-31",
     .m_Editions = {"Windows NT 4.0 Server", "Windows NT 4.0 Server Enterprise",
                    "Windows NT 4.0 Terminal Server Edition"},
     .m_Version = WindowsBuildInfo(4, 0, 1381, true, true)},

    /**
     * Windows XP Versions
     */
    {.m_szVersionName = "Windows XP",
     .m_szReleaseName = "",
     .m_szCodeName = "Whistler",
     .m_szReleaseDate = "2001-10-25",
     .m_szEolDate = "2014-04-08",
     .m_Editions = {"Windows XP Starter", "Windows XP Home", "Windows XP Professional", "Windows XP 64-bit Edition"},
     .m_Version = WindowsBuildInfo(5, 1, 2600, true)},
    {.m_szVersionName = "Windows XP Service Pack 1",
     .m_szReleaseName = "",
     .m_szCodeName = "Whistler",
     .m_szReleaseDate = "2002-09-09",
     .m_szEolDate = "2014-04-08",
     .m_Editions = {"Windows XP Starter", "Windows XP Home", "Windows XP Professional", "Windows XP 64-bit Edition"},
     .m_Version = WindowsBuildInfo(5, 1, 2600, true, false, 1)},
    {.m_szVersionName = "Windows XP Service Pack 2",
     .m_szReleaseName = "",
     .m_szCodeName = "Whistler",
     .m_szReleaseDate = "2004-08-25",
     .m_szEolDate = "2014-04-08",
     .m_Editions = {"Windows XP Starter", "Windows XP Home", "Windows XP Professional", "Windows XP 64-bit Edition"},
     .m_Version = WindowsBuildInfo(5, 1, 2600, true, false, 2)},
    {.m_szVersionName = "Windows XP Service Pack 3",
     .m_szReleaseName = "",
     .m_szCodeName = "Whistler",
     .m_szReleaseDate = "2008-04-21",
     .m_szEolDate = "2014-04-08",
     .m_Editions = {"Windows XP Starter", "Windows XP Home", "Windows XP Professional", "Windows XP 64-bit Edition"},
     .m_Version = WindowsBuildInfo(5, 1, 2600, true, false, 3)},
    {.m_szVersionName = "Windows XP",
     .m_szReleaseName = "Media Center",
     .m_szCodeName = "Freestyle",
     .m_szReleaseDate = "2002-10-29",
     .m_szEolDate = "2014-04-08",
     .m_Editions = {"Windows XP Media Center Edition"},
     .m_Version = WindowsBuildInfo(5, 1, 2600, true)},
    {.m_szVersionName = "Windows XP",
     .m_szReleaseName = "Media Center 2004",
     .m_szCodeName = "Harmony",
     .m_szReleaseDate = "2003-09-30",
     .m_szEolDate = "2014-04-08",
     .m_Editions = {"Windows XP Media Center Edition 2004"},
     .m_Version = WindowsBuildInfo(5, 1, 2600, true)},
    {.m_szVersionName = "Windows XP",
     .m_szReleaseName = "Media Center 2005",
     .m_szCodeName = "Symphony",
     .m_szReleaseDate = "2004-10-12",
     .m_szEolDate = "2014-04-08",
     .m_Editions = {"Windows XP Media Center Edition 2005"},
     .m_Version = WindowsBuildInfo(5, 1, 2700, true)},
    {.m_szVersionName = "Windows XP",
     .m_szReleaseName = "Media Center 2005 Update Rollup 2",
     .m_szCodeName = "Emerald",
     .m_szReleaseDate = "2005-10-14",
     .m_szEolDate = "2014-04-08",
     .m_Editions = {"Windows XP Media Center Edition 2005 Update Rollup 2"},
     .m_Version = WindowsBuildInfo(5, 1, 2710, true)},
    {.m_szVersionName = "Windows XP",
     .m_szReleaseName = "Professional x64",
     .m_szCodeName = "Anvil",
     .m_szReleaseDate = "2005-04-25",
     .m_szEolDate = "2014-04-08",
     .m_Editions = {"Windows XP Professional x64 Edition"},
     .m_Version = WindowsBuildInfo(5, 2, 3790, true)},

    /**
     * Windows 5.x Server Versions
     */
    {.m_szVersionName = "Windows 2000 Server",
     .m_szReleaseName = "",
     .m_szCodeName = "NT 5.0",
     .m_szReleaseDate = "2000-02-17",
     .m_szEolDate = "2010-07-13",
     .m_Editions = {"Windows 2000 Server Windows 2000 Advanced Server Windows 2000 Datacenter Server"},
     .m_Version = WindowsBuildInfo(5, 0, 2195, true, true)},
    {.m_szVersionName = "Windows Server 2003",
     .m_szReleaseName = "",
     .m_szCodeName = "Whistler Server",
     .m_szReleaseDate = "2003-04-24",
     .m_szEolDate = "2015-07-14",
     .m_Editions = {"Windows Server Web", "Windows Server Standard", "Windows Server Enterprise",
                    "Windows Server Datacenter", "Windows Storage Server"},
     .m_Version = WindowsBuildInfo(5, 2, 3790, true, true)},
    {.m_szVersionName = "Windows Server 2003 Service Pack 1",
     .m_szReleaseName = "",
     .m_szCodeName = "Whistler Server",
     .m_szReleaseDate = "2005-03-30",
     .m_szEolDate = "2015-07-14",
     .m_Editions = {"Windows Server Web", "Windows Server Standard", "Windows Server Enterprise",
                    "Windows Server Datacenter", "Windows Storage Server"},
     .m_Version = WindowsBuildInfo(5, 2, 3790, true, true, 1)},
    {.m_szVersionName = "Windows Server 2003 R2",
     .m_szReleaseName = "",
     .m_szCodeName = "Whistler Server",
     .m_szReleaseDate = "2005-12-06",
     .m_szEolDate = "2015-07-14",
     .m_Editions = {"Windows Server Web", "Windows Server Standard", "Windows Server Enterprise",
                    "Windows Server Datacenter", "Windows Storage Server"},
     .m_Version = WindowsBuildInfo(5, 2, 3790, true, true, 10)},
    {.m_szVersionName = "Windows Server 2003 Service Pack 2",
     .m_szReleaseName = "",
     .m_szCodeName = "Whistler Server",
     .m_szReleaseDate = "2007-03-13",
     .m_szEolDate = "2015-07-14",
     .m_Editions = {"Windows Server Web", "Windows Server Standard", "Windows Server Enterprise",
                    "Windows Server Datacenter", "Windows Storage Server"},
     .m_Version = WindowsBuildInfo(5, 2, 3790, true, true, 2)},
    {.m_szVersionName = "Windows Home Server",
     .m_szReleaseName = "",
     .m_szCodeName = "Whistler Server",
     .m_szReleaseDate = "2007-11-04",
     .m_szEolDate = "2015-07-14",
     .m_Editions = {"Home Server"},
     .m_Version = WindowsBuildInfo(5, 2, 4500, true, true)},

    /**
     * Windows 6.x Workstation Version
     */
    {.m_szVersionName = "Windows Vista",
     .m_szReleaseName = "",
     .m_szCodeName = "Longhorn",
     .m_szReleaseDate = "2007-01-30",
     .m_szEolDate = "2017-04-11",
     .m_Editions = {"Windows Vista Starter", "Windows Vista Home Basic", "Windows Vista Home Premium",
                    "Windows Vista Business", "Windows Vista Enterprise", "Windows Vista Ultimate"},
     .m_Version = WindowsBuildInfo(6, 0, 6000, true)},
    {.m_szVersionName = "Windows Vista Service Pack 1",
     .m_szReleaseName = "",
     .m_szCodeName = "Longhorn",
     .m_szReleaseDate = "2008-02-04",
     .m_szEolDate = "2017-04-11",
     .m_Editions = {"Windows Vista Starter", "Windows Vista Home Basic", "Windows Vista Home Premium",
                    "Windows Vista Business", "Windows Vista Enterprise", "Windows Vista Ultimate"},
     .m_Version = WindowsBuildInfo(6, 0, 6001, true)},
    {.m_szVersionName = "Windows Vista Service Pack 2",
     .m_szReleaseName = "",
     .m_szCodeName = "Longhorn",
     .m_szReleaseDate = "2009-05-26",
     .m_szEolDate = "2017-04-11",
     .m_Editions = {"Windows Vista Starter", "Windows Vista Home Basic", "Windows Vista Home Premium",
                    "Windows Vista Business", "Windows Vista Enterprise", "Windows Vista Ultimate"},
     .m_Version = WindowsBuildInfo(6, 0, 6002, true)},
    {.m_szVersionName = "Windows 7",
     .m_szReleaseName = "",
     .m_szCodeName = "Windows 7",
     .m_szReleaseDate = "2009-10-22",
     .m_szEolDate = "2020-01-14",
     .m_Editions = {"Windows 7 Starter", "Windows 7 Home Basic", "Windows 7 Home Premium", "Windows 7 Professional",
                    "Windows 7 Enterprise", "Windows 7 Ultimate"},
     .m_Version = WindowsBuildInfo(6, 1, 7600, true)},
    {.m_szVersionName = "Windows 7 Service Pack 1",
     .m_szReleaseName = "",
     .m_szCodeName = "Windows 7",
     .m_szReleaseDate = "2011-02-22",
     .m_szEolDate = "2020-01-14",
     .m_Editions = {"Windows 7 Starter", "Windows 7 Home Basic", "Windows 7 Home Premium", "Windows 7 Professional",
                    "Windows 7 Enterprise", "Windows 7 Ultimate"},
     .m_Version = WindowsBuildInfo(6, 1, 7601, true)},
    {.m_szVersionName = "Windows 8",
     .m_szReleaseName = "",
     .m_szCodeName = "Windows 8",
     .m_szReleaseDate = "2012-10-26",
     .m_szEolDate = "2016-01-12",
     .m_Editions = {"Windows 8", "Windows 8 Pro", "Windows 8 Enterprise"},
     .m_Version = WindowsBuildInfo(6, 2, 9200, true)},
    {.m_szVersionName = "Windows 8.1",
     .m_szReleaseName = "",
     .m_szCodeName = "Blue",
     .m_szReleaseDate = "2013-10-17",
     .m_szEolDate = "2023-01-10",
     .m_Editions = {"Windows 8.1", "Windows 8.1 Pro", "Windows 8.1 Enterprise"},
     .m_Version = WindowsBuildInfo(6, 3, 9600, true)},
    {.m_szVersionName = "Windows 8.1",
     .m_szReleaseName = "with Bing",
     .m_szCodeName = "Blue",
     .m_szReleaseDate = "2014-05-23",
     .m_szEolDate = "2023-01-10",
     .m_Editions = {"Windows 8.1 with Bing"},
     .m_Version = WindowsBuildInfo(6, 3, 9600, true)},

    /**
     * Windows 6.x Server Versions
     */
    {.m_szVersionName = "Windows Server 2008",
     .m_szReleaseName = "",
     .m_szCodeName = "Longhorn Server",
     .m_szReleaseDate = "2008-02-27",
     .m_szEolDate = "2020-01-14",
     .m_Editions = {"Windows Server Foundation", "Windows Server Standard", "Windows Server Enterprise",
                    "Windows Server Datacenter", "Windows Server for Itanium-based Systems", "Windows Storage Server",
                    "Windows Web Server"},
     .m_Version = WindowsBuildInfo(6, 0, 6001, true, true)},
    {.m_szVersionName = "Windows Server 2008 Service Pack 2",
     .m_szReleaseName = "",
     .m_szCodeName = "Longhorn Server",
     .m_szReleaseDate = "2009-05-26",
     .m_szEolDate = "2020-01-14",
     .m_Editions = {"Windows Server Foundation", "Windows Server Standard", "Windows Server Enterprise",
                    "Windows Server Datacenter", "Windows Server for Itanium-based Systems", "Windows Storage Server",
                    "Windows Web Server"},
     .m_Version = WindowsBuildInfo(6, 0, 6002, true, true)},
    {.m_szVersionName = "Windows Server 2008 Service Pack 2, Rollup KB4489887",
     .m_szReleaseName = "",
     .m_szCodeName = "Longhorn Server",
     .m_szReleaseDate = "2019-03-19",
     .m_szEolDate = "2020-01-14",
     .m_Editions = {"Windows Server Foundation", "Windows Server Standard", "Windows Server Enterprise",
                    "Windows Server Datacenter", "Windows Server for Itanium-based Systems", "Windows Storage Server",
                    "Windows Web Server"},
     .m_Version = WindowsBuildInfo(6, 0, 6003, true, true)},
    {.m_szVersionName = "Windows Server 2008 R2",
     .m_szReleaseName = "",
     .m_szCodeName = "Windows Server 7",
     .m_szReleaseDate = "2009-10-22",
     .m_szEolDate = "2020-01-14",
     .m_Editions = {"Windows Server Foundation", "Windows Server Standard", "Windows Server Enterprise",
                    "Windows Server Datacenter", "Windows Server for Itanium-based Systems", "Windows Storage Server",
                    "Windows Web Server"},
     .m_Version = WindowsBuildInfo(6, 1, 7600, true, true)},
    {.m_szVersionName = "Windows Server 2008 R2 Service Pack 1",
     .m_szReleaseName = "",
     .m_szCodeName = "Windows Server 7",
     .m_szReleaseDate = "2011-02-22",
     .m_szEolDate = "2020-01-14",
     .m_Editions = {"Windows Server Foundation", "Windows Server Standard", "Windows Server Enterprise",
                    "Windows Server Datacenter", "Windows Server for Itanium-based Systems", "Windows Storage Server",
                    "Windows Web Server"},
     .m_Version = WindowsBuildInfo(6, 1, 7601, true, true)},
    {.m_szVersionName = "Windows Home Server 2011",
     .m_szReleaseName = "",
     .m_szCodeName = "Windows Server 7",
     .m_szReleaseDate = "2011-04-06",
     .m_szEolDate = "2020-01-14",
     .m_Editions = {"Home Server"},
     .m_Version = WindowsBuildInfo(6, 1, 8400, true, true)},
    {.m_szVersionName = "Windows Server 2012",
     .m_szReleaseName = "",
     .m_szCodeName = "Windows Server 8",
     .m_szReleaseDate = "2012-09-04",
     .m_szEolDate = "2023-10-10",
     .m_Editions = {"Windows Server Foundation", "Windows Server Essentials", "Windows Server Standard",
                    "Windows Server Datacenter"},
     .m_Version = WindowsBuildInfo(6, 2, 9200, true, true)},
    {.m_szVersionName = "Windows Server 2012 R2",
     .m_szReleaseName = "",
     .m_szCodeName = "Windows Server Blue",
     .m_szReleaseDate = "2013-10-17",
     .m_szEolDate = "2023-10-10",
     .m_Editions = {"Windows Server Foundation", "Windows Server Essentials", "Windows Server Standard",
                    "Windows Server Datacenter"},
     .m_Version = WindowsBuildInfo(6, 3, 9600, true, true)},

    /**
     * Windows 10 Workstation Versions
     */
    {.m_szVersionName = "Windows 10",
     .m_szReleaseName = "1507 (Initial Update)",
     .m_szCodeName = "Threshold",
     .m_szReleaseDate = "2015-07-29",
     .m_szEolDate = "2025-10-14",
     .m_Editions = {"Windows 10 Home", "Windows 10 Pro", "Windows 10 Education", "Windows 10 Enterprise",
                    "Windows 10 Pro for Workstations", "Windows 10 Pro Education", "Windows 10 S",
                    "Windows 10 Enterprise LTSC"},
     .m_Version = WindowsBuildInfo(10, 0, 10240, true)},
    {.m_szVersionName = "Windows 10",
     .m_szReleaseName = "1511 (November Update)",
     .m_szCodeName = "Threshold 2",
     .m_szReleaseDate = "2015-11-10",
     .m_szEolDate = "2025-10-14",
     .m_Editions = {"Windows 10 Home", "Windows 10 Pro", "Windows 10 Education", "Windows 10 Enterprise",
                    "Windows 10 Pro for Workstations", "Windows 10 Pro Education", "Windows 10 S",
                    "Windows 10 Enterprise LTSC"},
     .m_Version = WindowsBuildInfo(10, 0, 10586, true)},
    {.m_szVersionName = "Windows 10",
     .m_szReleaseName = "1607 (Anniversary Update)",
     .m_szCodeName = "Redstone 1",
     .m_szReleaseDate = "2016-08-02",
     .m_szEolDate = "2025-10-14",
     .m_Editions = {"Windows 10 Home", "Windows 10 Pro", "Windows 10 Education", "Windows 10 Enterprise",
                    "Windows 10 Pro for Workstations", "Windows 10 Pro Education", "Windows 10 S",
                    "Windows 10 Enterprise LTSC"},
     .m_Version = WindowsBuildInfo(10, 0, 14393, true)},
    {.m_szVersionName = "Windows 10",
     .m_szReleaseName = "1703 (Creators Update)",
     .m_szCodeName = "Redstone 2",
     .m_szReleaseDate = "2017-04-05",
     .m_szEolDate = "2025-10-14",
     .m_Editions = {"Windows 10 Home", "Windows 10 Pro", "Windows 10 Education", "Windows 10 Enterprise",
                    "Windows 10 Pro for Workstations", "Windows 10 Pro Education", "Windows 10 S",
                    "Windows 10 Enterprise LTSC"},
     .m_Version = WindowsBuildInfo(10, 0, 15063, true)},
    {.m_szVersionName = "Windows 10",
     .m_szReleaseName = "1709 (Fall Creators Update)",
     .m_szCodeName = "Redstone 3",
     .m_szReleaseDate = "2017-10-17",
     .m_szEolDate = "2025-10-14",
     .m_Editions = {"Windows 10 Home", "Windows 10 Pro", "Windows 10 Education", "Windows 10 Enterprise",
                    "Windows 10 Pro for Workstations", "Windows 10 Pro Education", "Windows 10 S",
                    "Windows 10 Enterprise LTSC"},
     .m_Version = WindowsBuildInfo(10, 0, 16299, true)},
    {.m_szVersionName = "Windows 10",
     .m_szReleaseName = "1803 (April 2018 Update)",
     .m_szCodeName = "Redstone 4",
     .m_szReleaseDate = "2018-04-30",
     .m_szEolDate = "2025-10-14",
     .m_Editions = {"Windows 10 Home", "Windows 10 Pro", "Windows 10 Education", "Windows 10 Enterprise",
                    "Windows 10 Pro for Workstations", "Windows 10 Pro Education", "Windows 10 S",
                    "Windows 10 Enterprise LTSC"},
     .m_Version = WindowsBuildInfo(10, 0, 17134, true)},
    {.m_szVersionName = "Windows 10",
     .m_szReleaseName = "1809 (October 2018 Update)",
     .m_szCodeName = "Redstone 5",
     .m_szReleaseDate = "2018-11-13",
     .m_szEolDate = "2025-10-14",
     .m_Editions = {"Windows 10 Home", "Windows 10 Pro", "Windows 10 Education", "Windows 10 Enterprise",
                    "Windows 10 Pro for Workstations", "Windows 10 Pro Education", "Windows 10 S",
                    "Windows 10 Enterprise LTSC"},
     .m_Version = WindowsBuildInfo(10, 0, 17763, true)},
    {.m_szVersionName = "Windows 10",
     .m_szReleaseName = "1903 (May 2019 Update)",
     .m_szCodeName = "19H1",
     .m_szReleaseDate = "2019-05-21",
     .m_szEolDate = "2025-10-14",
     .m_Editions = {"Windows 10 Home", "Windows 10 Pro", "Windows 10 Education", "Windows 10 Enterprise",
                    "Windows 10 Pro for Workstations", "Windows 10 Pro Education", "Windows 10 S",
                    "Windows 10 Enterprise LTSC"},
     .m_Version = WindowsBuildInfo(10, 0, 18362, true)},
    {.m_szVersionName = "Windows 10",
     .m_szReleaseName = "1909 (November 2019 Update)",
     .m_szCodeName = "Vanadium",
     .m_szReleaseDate = "2019-11-12",
     .m_szEolDate = "2025-10-14",
     .m_Editions = {"Windows 10 Home", "Windows 10 Pro", "Windows 10 Education", "Windows 10 Enterprise",
                    "Windows 10 Pro for Workstations", "Windows 10 Pro Education", "Windows 10 S",
                    "Windows 10 Enterprise LTSC"},
     .m_Version = WindowsBuildInfo(10, 0, 18363, true)},
    {.m_szVersionName = "Windows 10",
     .m_szReleaseName = "2004",
     .m_szCodeName = "Vibranium",
     .m_szReleaseDate = "2020-05-27",
     .m_szEolDate = "2025-10-14",
     .m_Editions = {"Windows 10 Home", "Windows 10 Pro", "Windows 10 Education", "Windows 10 Enterprise",
                    "Windows 10 Pro for Workstations", "Windows 10 Pro Education", "Windows 10 S",
                    "Windows 10 Enterprise LTSC"},
     .m_Version = WindowsBuildInfo(10, 0, 19041, true)},
    {.m_szVersionName = "Windows 10",
     .m_szReleaseName = "20H2",
     .m_szCodeName = "Vibranium",
     .m_szReleaseDate = "2020-10-20",
     .m_szEolDate = "2025-10-14",
     .m_Editions = {"Windows 10 Home", "Windows 10 Pro", "Windows 10 Education", "Windows 10 Enterprise",
                    "Windows 10 Pro for Workstations", "Windows 10 Pro Education", "Windows 10 S",
                    "Windows 10 Enterprise LTSC"},
     .m_Version = WindowsBuildInfo(10, 0, 19042, true)},
    {.m_szVersionName = "Windows 10",
     .m_szReleaseName = "21H1",
     .m_szCodeName = "Vibranium",
     .m_szReleaseDate = "2021-05-18",
     .m_szEolDate = "2025-10-14",
     .m_Editions = {"Windows 10 Home", "Windows 10 Pro", "Windows 10 Education", "Windows 10 Enterprise",
                    "Windows 10 Pro for Workstations", "Windows 10 Pro Education", "Windows 10 S",
                    "Windows 10 Enterprise LTSC"},
     .m_Version = WindowsBuildInfo(10, 0, 19043, true)},
    {.m_szVersionName = "Windows 10",
     .m_szReleaseName = "21H2",
     .m_szCodeName = "Vibranium",
     .m_szReleaseDate = "2021-11-16",
     .m_szEolDate = "2025-10-14",
     .m_Editions = {"Windows 10 Home", "Windows 10 Pro", "Windows 10 Education", "Windows 10 Enterprise",
                    "Windows 10 Pro for Workstations", "Windows 10 Pro Education", "Windows 10 S",
                    "Windows 10 Enterprise LTSC"},
     .m_Version = WindowsBuildInfo(10, 0, 19044, true)},
    {.m_szVersionName = "Windows 10",
     .m_szReleaseName = "22H2",
     .m_szCodeName = "Vibranium",
     .m_szReleaseDate = "2022-10-18",
     .m_szEolDate = "2025-10-14",
     .m_Editions = {"Windows 10 Home", "Windows 10 Pro", "Windows 10 Education", "Windows 10 Enterprise",
                    "Windows 10 Pro for Workstations", "Windows 10 Pro Education", "Windows 10 S",
                    "Windows 10 Enterprise LTSC"},
     .m_Version = WindowsBuildInfo(10, 0, 19045, true)},

    /**
     * Windows 11 Versions
     */
    {.m_szVersionName = "Windows 11",
     .m_szReleaseName = "21H2",
     .m_szCodeName = "Cobalt/Sun Valley",
     .m_szReleaseDate = "2021-10-05",
     .m_szEolDate = "2023-10-10",
     .m_Editions = {"Windows 11 Home", "Windows 11 Pro", "Windows 11 Pro for Workstations", "Windows 11 Pro Education",
                    "Windows 11 Education", "Windows 11 Enterprise", "Windows 11 SE"},
     .m_Version = WindowsBuildInfo(10, 0, 22000, true)},
    {.m_szVersionName = "Windows 11",
     .m_szReleaseName = "22H2",
     .m_szCodeName = "Nickel/Sun Valley 2",
     .m_szReleaseDate = "2022-09-20",
     .m_szEolDate = "2024-10-08",
     .m_Editions = {"Windows 11 Home", "Windows 11 Pro", "Windows 11 Pro for Workstations", "Windows 11 Pro Education",
                    "Windows 11 Education", "Windows 11 Enterprise", "Windows 11 SE"},
     .m_Version = WindowsBuildInfo(10, 0, 22621, true)},
    {.m_szVersionName = "Windows 11",
     .m_szReleaseName = "23H2",
     .m_szCodeName = "Nickel",
     .m_szReleaseDate = "2023-10-31",
     .m_szEolDate = "2025-11-11",
     .m_Editions = {"Windows 11 Home", "Windows 11 Pro", "Windows 11 Pro for Workstations", "Windows 11 Pro Education",
                    "Windows 11 Education", "Windows 11 Enterprise", "Windows 11 SE"},
     .m_Version = WindowsBuildInfo(10, 0, 22631, true)},
    {.m_szVersionName = "Windows 11",
     .m_szReleaseName = "24H2",
     .m_szCodeName = "Germanium",
     .m_szReleaseDate = "2024-10-01",
     .m_szEolDate = "2026-10-13",
     .m_Editions = {"Windows 11 Home", "Windows 11 Pro", "Windows 11 Pro for Workstations", "Windows 11 Pro Education",
                    "Windows 11 Education", "Windows 11 Enterprise", "Windows 11 SE"},
     .m_Version = WindowsBuildInfo(10, 0, 26100, true)},

    /**
     * Windows 10 Server Versions
     */
    {.m_szVersionName = "Windows Server 2016",
     .m_szReleaseName = "1607",
     .m_szCodeName = "",
     .m_szReleaseDate = "2016-10-12",
     .m_szEolDate = "2027-01-12",
     .m_Editions = {"Windows Server Essentials[s]", "Windows Server Standard", "Windows Server Datacenter"},
     .m_Version = WindowsBuildInfo(10, 0, 14393, true, true)},
    {.m_szVersionName = "Windows Server",
     .m_szReleaseName = "1709",
     .m_szCodeName = "",
     .m_szReleaseDate = "2017-10-17",
     .m_szEolDate = "2019-04-09",
     .m_Editions = {"Windows Server Essentials[s]", "Windows Server Standard", "Windows Server Datacenter"},
     .m_Version = WindowsBuildInfo(10, 0, 16299, true, true)},
    {.m_szVersionName = "Windows Server",
     .m_szReleaseName = "1803",
     .m_szCodeName = "",
     .m_szReleaseDate = "2018-04-30",
     .m_szEolDate = "2019-11-12",
     .m_Editions = {"Windows Server Essentials[s]", "Windows Server Standard", "Windows Server Datacenter"},
     .m_Version = WindowsBuildInfo(10, 0, 17134, true, true)},
    {.m_szVersionName = "Windows Server 2019",
     .m_szReleaseName = "",
     .m_szCodeName = "",
     .m_szReleaseDate = "2018-11-13",
     .m_szEolDate = "2029-01-09",
     .m_Editions = {"Windows Server Essentials[s]", "Windows Server Standard", "Windows Server Datacenter"},
     .m_Version = WindowsBuildInfo(10, 0, 17763, true, true)},
    {.m_szVersionName = "Windows Server",
     .m_szReleaseName = "1903",
     .m_szCodeName = "",
     .m_szReleaseDate = "2019-05-21",
     .m_szEolDate = "2020-12-08",
     .m_Editions = {"Windows Server Essentials[s]", "Windows Server Standard", "Windows Server Datacenter"},
     .m_Version = WindowsBuildInfo(10, 0, 18362, true, true)},
    {.m_szVersionName = "Windows Server",
     .m_szReleaseName = "1909",
     .m_szCodeName = "",
     .m_szReleaseDate = "2019-11-12",
     .m_szEolDate = "2021-05-11",
     .m_Editions = {"Windows Server Essentials[s]", "Windows Server Standard", "Windows Server Datacenter"},
     .m_Version = WindowsBuildInfo(10, 0, 18363, true, true)},
    {.m_szVersionName = "Windows Server",
     .m_szReleaseName = "2004",
     .m_szCodeName = "",
     .m_szReleaseDate = "2020-06-26",
     .m_szEolDate = "2021-12-14",
     .m_Editions = {"Windows Server Essentials[s]", "Windows Server Standard", "Windows Server Datacenter"},
     .m_Version = WindowsBuildInfo(10, 0, 19041, true, true)},
    {.m_szVersionName = "Windows Server",
     .m_szReleaseName = "20H2",
     .m_szCodeName = "",
     .m_szReleaseDate = "2020-10-20",
     .m_szEolDate = "2022-08-09",
     .m_Editions = {"Windows Server Essentials[s]", "Windows Server Standard", "Windows Server Datacenter"},
     .m_Version = WindowsBuildInfo(10, 0, 19042, true, true)},
    {.m_szVersionName = "Windows Server 2022",
     .m_szReleaseName = "",
     .m_szCodeName = "",
     .m_szReleaseDate = "2021-08-18",
     .m_szEolDate = "2031-10-14",
     .m_Editions = {"Windows Server Essentials[s]", "Windows Server Standard", "Windows Server Datacenter"},
     .m_Version = WindowsBuildInfo(10, 0, 20348, true, true)},
    {.m_szVersionName = "Windows Server",
     .m_szReleaseName = "23H2",
     .m_szCodeName = "",
     .m_szReleaseDate = "2023-10-14",
     .m_szEolDate = "2025-10-24",
     .m_Editions = {"Windows Server Essentials[s]", "Windows Server Standard", "Windows Server Datacenter"},
     .m_Version = WindowsBuildInfo(10, 0, 25398, true, true)}};
